theme: minima
title: Shik's Chatroom
author: ShikhaaT44
email: shikhatikiwala@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Technology, Cloud Computing and much more 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
